apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: test-app-hello
  namespace: test-app
spec:
  endpoints:
  - path: /metrics
    port: http
  selector:
    matchLabels:
      app: test-app-hello
