apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-app-hello-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-app-hello
spec:
  hosts:
  - "*"
  gateways:
  - test-app-hello-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: test-app-hello.test-app.svc.cluster.local
        port:
          number: 80

