---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: redis
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
